name: social_project
description: Social project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  wpmodel:
    path: ../wp_model/

  shared:
    path: ../_shared/

  outline_material_icons: ^0.1.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter:
  flutter_localizations:
    sdk: flutter
  chewie: ^0.9.10
  video_player: ^0.10.8+1
  audioplayerui: ^0.0.7
  extended_image: ^0.7.3-dev
  like_button: ^0.2.0
  extended_text: any
  url_launcher: ^5.0.2
  isolate: ^2.0.2
  image_editor: ^0.1.2
  #  image_picker_saver: 0.3.0
  image_picker: 0.6.3+1
#  zefyr: ^0.10.0
  image_gallery_saver: ^1.2.2
  flutter_statusbarcolor: ^0.2.3
  flutter_banner_swiper: ^0.1.4
  flutter_screenutil: ^1.0.2
  xml: ^3.5.0
  steel_crypt: any  #ANDROID IOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  ff_annotation_route: any

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/gooey_edge/Open-Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/gooey_edge/DM-Serif-Display/DMSerifDisplay-Regular.ttf
        - asset: assets/fonts/gooey_edge/DM-Serif-Display/DMSerifDisplay-Italic.ttf
          style: italic